command_timeout = 500
add_newline = true

format = """
[┌─  ](bold green)$username$hostname$directory$git_branch$git_status
[└─](bold green)$character"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[username]
style_user = "bold yellow"
style_root = "bold red"
format = "[$user]($style) "
disabled = false
show_always = false

[directory]
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold cyan"
read_only = " 🔒"
read_only_style = "red"
truncation_symbol = "…/"

[git_branch]
symbol = "🌱 "
format = "[$symbol$branch]($style) "
style = "bold purple"
truncation_length = 35
truncation_symbol = "…"

[git_status]
style = "bold yellow"

[package]
disabled = true
